// <auto-generated />
namespace EvaluatingWebsitePerformance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitEntities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitEntities));
        
        string IMigrationMetadata.Id
        {
            get { return "202101052002237_InitEntities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
